project:
  type: website

website:
  title: "Marc GAREL"
  navbar:
    left:
      - href: index.qmd
        text: "🏠 Accueil"
      - href: about.qmd
        text: "👤 À propos"
      - href: cv.qmd
        text: "📄 CV"
      - href: blog/index.qmd
        text: "📝 Blog"
      - href: portfolio/index.qmd
        text: "💼 Portfolio"
      - href: recherche.qmd
        text: "🔬 Recherche"
      - href: publications/index.qmd
        text: "📚 Publications"
    right:
      - icon: github
        href: https://github.com/marcgarel/mapageperso.io
  page-footer:
    left: "© 2026 Marc GAREL"
    right: "Site créé avec [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true