project:
  type: website

website:
  title: "Marc Garel"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: recherche.qmd
        text: Recherche
      - href: blog/index.qmd
        text: Blog
      - href: portfolio/index.qmd
        text: Portfolio
      - href: publications/index.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/ 
      - icon: twitter
        href: https://twitter.com/
      - icon: envelope
        href: mailto:marc.garel@cnrs.fr

  page-footer:
    left: "© 2026 Marc Garel"
    right: 
      - icon: mortarboard
        href: https://orcid.org/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: css/styles.css
    toc: true
    code-fold: true
    code-copy: true
    highlight-style: github

editor: visual
